default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: suky
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: workspace_development

test:
  <<: *default
  database: workspace_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
